# Generated by Django 6.0.6 on 2026-06-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
