# Generated by Django 6.0.6 on 2026-06-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(default='Gold', max_length=50),
        ),
    ]
