# Generated by Django 6.0.6 on 2026-07-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_image_url_review_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
    ]
